import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CategoriesBar from "./components/CategoriesBar";
import SessionWrapper from "./components/SessionWrapper";
import { Toaster } from "sonner";
import ProviderWrapper from "./components/ProviderWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProviderWrapper>
          <SessionWrapper>
            <Navbar />
            <CategoriesBar />
            {children}
          </SessionWrapper>
        </ProviderWrapper>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
